
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'rightPOWERleftMULTDIVleftPLUSMINUSrightUMINUSDIV EQUAL ID LPAREN MINUS MULT NUM PLUS POWER RPARENstatement : ID EQUAL expressionexpression : expression PLUS expression\n                  | expression MINUS expression\n                  | expression MULT expression\n                  | expression DIV expressionexpression : expression POWER expressionexpression : MINUS expression %prec UMINUSexpression : LPAREN expression RPARENexpression : NUMexpression : ID'
    
_lr_action_items = {'ID':([0,3,6,7,9,10,11,12,13,],[2,4,4,4,4,4,4,4,4,]),'$end':([1,4,5,8,14,16,17,18,19,20,21,],[0,-10,-1,-9,-7,-2,-3,-4,-5,-6,-8,]),'EQUAL':([2,],[3,]),'MINUS':([3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,],[6,-10,10,6,6,-9,6,6,6,6,6,-7,10,-2,-3,10,10,10,-8,]),'LPAREN':([3,6,7,9,10,11,12,13,],[7,7,7,7,7,7,7,7,]),'NUM':([3,6,7,9,10,11,12,13,],[8,8,8,8,8,8,8,8,]),'PLUS':([4,5,8,14,15,16,17,18,19,20,21,],[-10,9,-9,-7,9,-2,-3,9,9,9,-8,]),'MULT':([4,5,8,14,15,16,17,18,19,20,21,],[-10,11,-9,-7,11,-2,-3,-4,-5,11,-8,]),'DIV':([4,5,8,14,15,16,17,18,19,20,21,],[-10,12,-9,-7,12,-2,-3,-4,-5,12,-8,]),'POWER':([4,5,8,14,15,16,17,18,19,20,21,],[-10,13,-9,-7,13,-2,-3,-4,-5,13,-8,]),'RPAREN':([4,8,14,15,16,17,18,19,20,21,],[-10,-9,-7,21,-2,-3,-4,-5,-6,-8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[1,]),'expression':([3,6,7,9,10,11,12,13,],[5,14,15,16,17,18,19,20,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> ID EQUAL expression','statement',3,'p_statement_assign','power.py',65),
  ('expression -> expression PLUS expression','expression',3,'p_expression_binop','power.py',71),
  ('expression -> expression MINUS expression','expression',3,'p_expression_binop','power.py',72),
  ('expression -> expression MULT expression','expression',3,'p_expression_binop','power.py',73),
  ('expression -> expression DIV expression','expression',3,'p_expression_binop','power.py',74),
  ('expression -> expression POWER expression','expression',3,'p_expression_power','power.py',81),
  ('expression -> MINUS expression','expression',2,'p_expression_uminus','power.py',88),
  ('expression -> LPAREN expression RPAREN','expression',3,'p_expression_group','power.py',95),
  ('expression -> NUM','expression',1,'p_expression_num','power.py',99),
  ('expression -> ID','expression',1,'p_expression_id','power.py',103),
]
